name: ${PROJECT_NAME}

services:
  api:
    image: bref/php-82-fpm-dev:2
    container_name: "${PROJECT_NAME}-api"
    ports: ['8001:8000']
    volumes:
      - .:/var/task
    environment:
      HANDLER: htdocs/index.php
      # Assets will be served from this directory
      DOCUMENT_ROOT: public
      PHP_INI_SCAN_DIR: /var/task/config/php
      DB_MYSQL_HOST: "${PROJECT_NAME}-db-mysql:3306"

  db-mysql:
    image: mysql:8.4.4
    container_name: "${PROJECT_NAME}-db-mysql"
    environment:
      MYSQL_ROOT_PASSWORD: OxAk5S-vS3_
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${DB_MYSQL_DATABASE}
    ports:
      - "3310:3306"
    volumes:
      - db-mysql-data:/var/lib/mysql
      - ./config/mysql:/etc/mysql/conf.d
      - ./init/mysql:/docker-entrypoint-initdb.d:ro

  db-dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: "${PROJECT_NAME}-db-dynamodb-local"
    ports:
      - "8010:8000"
    environment:
      - AWS_REGION=${DB_DYNAMO_REGION}
      - AWS_ACCESS_KEY_ID=${DB_DYNAMO_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${DB_DYNAMO_SECRET_ACCESS_KEY}
    volumes:
      - "./.docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

volumes:
  db-mysql-data: